version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/g0tiu5a/g0tiu5a-bot

    steps:
      - checkout
      # to install glide
      # Cache glide.sh
      - restore_cache:
          keys: glide-{{ checksum "/tmp/get_glide" }}
      - run: curl https://glide.sh/get > /tmp/get_glide && sh /tmp/get_glide
      - save_cache:
          key: glide-{{ checksum "/tmp/get_glide" }}
          paths: /tmp/get_glide

      # Cache vendor/
      - restore_cache:
          keys: glide-cache-{{ checksum "glide.lock" }}
      - run: glide install
      - save_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
          paths: vendor/

      - run: go get -v -t -d ./...
      - run: go build
      - run: go test -v $(go list ./... | grep -v /vendor/)
